### ISSUE TITLE
/last or /previous or /latest

### ISSUE THREAD

**Issue by ask-compu** [Xe/PonyAPI#1]
could u add one of these to give the last episode of mlp that aired?

**Comment by jaredallard** [comment]
:+1: For now you could get `/newest` and use some logic to get the last episode.

**Comment by ask-compu** [comment]
but newest only gives one episode, the next one to air, right?

**Comment by ask-compu** [comment]
for now i have a temporary bit of code set to just give season 5 episode 13 for last

**Comment by jaredallard** [comment]
Yes, but you could use logic (with the ep & season number) to go back and ep (the last aired one) and if needed go back a season.

**Comment by Xe** [comment]
``` python
# last_aired :: IO Episode
# TODO: Does not know how to wrap around seasons, fix this
def last_aired():
    new = newest()

    if new[u"air_date"] > int(time.time()):
        return get_episode(new[u"season"], (new[u"episode"]-1))
    return new
```

Also keep in mind that this API has no use limits, so making multiple API calls is fine.
