### ISSUE TITLE
Add last_aired route

### ISSUE THREAD

**Issue by Xe** [Xe/PonyAPI#3]
For @ask-compu

**Comment by Xe** [comment]
This is in progress locally.

**Comment by Xe** [comment]
Fixed in b5d36da2b6b1a4b07c9d22666ee39284ad9f57e7

**Comment by ask-compu** [comment]
cool, thanks so much ^_^

**Comment by ask-compu** [comment]
updated my bot https://github.com/ask-compu/CompuBot/commit/dd5b5bbb36ea77692ee4db5e5ac5a408c2d50a92
